#!/bin/zsh

if ! sudo -n true 2>/dev/null; then
  echo "Installing, asking for sudo password in advance."
  sudo -v
fi
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Get the path of this file
DIR="$( cd "$( dirname "$0:A" )" && pwd )"

# Get the system type
SYS=$(uname | awk '{print tolower($0)}')

# Create zshrc if it does not already exist
if [ ! -f ~/.zshrc ]; then
  touch ~/.zshrc
fi

# Source our library in zshrc
if ! grep -q "source $DIR/source" ~/.zshrc; then
  echo "source $DIR/source" >> ~/.zshrc
fi

# Run all install scripts
for D in  `find $DIR -maxdepth 1 -type d ! -name ".*" | sort`
do
  for F in `find $D -maxdepth 1 -type f -name "install.zsh" | sort`
  do
    source $F
  done
done

# Run system specific package install scripts
# Source system specific files
for D in  `find $DIR -maxdepth 1 -type d ! -name ".*" | sort`
do
  for DD in `find $D -maxdepth 1 -type d -name $SYS | sort`
  do
    for F in `find $DD -maxdepth 1 -type f -name "install.zsh" | sort`
    do
      source $F
    done
  done
done

# Sym link files
for D in `find $DIR -maxdepth 1 -type d ! -name ".*" | sort`
do
  for DD in `find $D -maxdepth 1 -type d -name "sym" | sort`
  do
    for F in `find $DD -maxdepth 1 -type f | sort`
    do
      echo Linking $F to ~/$(basename "$F")
      if [ -f ~/$(basename "$F") ]; then
        echo -n "~/$(basename $F) already exists. Overwrite [y/N]:"
        read OVERWRITE
        if [ "$OVERWRITE" = "y" ]; then
          echo "Overwriting ~/$(basename $F)"
          rm ~/$(basename "$F")
          ln -s $F ~/$(basename "$F")
        fi
      else
        ln -s $F ~/$(basename "$F")
      fi
    done
  done
done

# Source our .zshrc
source ~/.zshrc
