set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'niksingh710/minimal-tmux-status'
bind-key t set-option -g status

run '$HOME/.config/tmux/plugins/tpm/tpm'
TMUX_FZF_LAUNCH_KEY="C-f"

set -g mouse on
